[2024-12-14T11:08:20.861+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2024-12-14T10:53:00.802230+00:00 [queued]>
[2024-12-14T11:08:20.877+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2024-12-14T10:53:00.802230+00:00 [queued]>
[2024-12-14T11:08:20.878+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-12-14T11:08:20.902+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): kafka_data_stream> on 2024-12-14 10:53:00.802230+00:00
[2024-12-14T11:08:20.911+0000] {standard_task_runner.py:57} INFO - Started process 1415 to run task
[2024-12-14T11:08:20.920+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_dag', 'kafka_data_stream', 'scheduled__2024-12-14T10:53:00.802230+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmp_5cki1ss']
[2024-12-14T11:08:20.926+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask kafka_data_stream
[2024-12-14T11:08:21.036+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2024-12-14T10:53:00.802230+00:00 [running]> on host 5ca304857530
[2024-12-14T11:08:21.201+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_dag' AIRFLOW_CTX_TASK_ID='kafka_data_stream' AIRFLOW_CTX_EXECUTION_DATE='2024-12-14T10:53:00.802230+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-14T10:53:00.802230+00:00'
[2024-12-14T11:08:26.405+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.3', 9092)]>: connecting to kafka:9092 [('172.18.0.3', 9092) IPv4]
[2024-12-14T11:08:26.407+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-12-14T11:08:26.410+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.3', 9092)]>: Connection complete.
[2024-12-14T11:08:26.523+0000] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2024-12-14T11:08:26.525+0000] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2024-12-14T11:09:05.107+0000] {kafka_stream_data.py:95} INFO - Fetched 25 submissions from r/soccer
[2024-12-14T11:09:56.781+0000] {kafka_stream_data.py:95} INFO - Fetched 25 submissions from r/football
[2024-12-14T11:09:56.783+0000] {kafka_stream_data.py:113} INFO - Fetched 50 submissions from Reddit
[2024-12-14T11:09:56.796+0000] {conn.py:380} INFO - <BrokerConnection node_id=0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.3', 9092)]>: connecting to kafka:9092 [('172.18.0.3', 9092) IPv4]
[2024-12-14T11:09:56.801+0000] {conn.py:410} INFO - <BrokerConnection node_id=0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.3', 9092)]>: Connection complete.
[2024-12-14T11:09:56.804+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.3', 9092)]>: Closing connection. 
[2024-12-14T11:09:56.908+0000] {kafka_stream_data.py:123} INFO - Successfully sent data to Kafka
[2024-12-14T11:11:34.921+0000] {kafka_stream_data.py:95} INFO - Fetched 25 submissions from r/soccer
[2024-12-14T11:12:38.256+0000] {kafka_stream_data.py:95} INFO - Fetched 25 submissions from r/football
[2024-12-14T11:12:38.258+0000] {kafka_stream_data.py:113} INFO - Fetched 50 submissions from Reddit
[2024-12-14T11:12:38.324+0000] {kafka_stream_data.py:123} INFO - Successfully sent data to Kafka
[2024-12-14T11:12:46.111+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2024-12-14T11:12:46.135+0000] {process_utils.py:131} INFO - Sending 15 to group 1415. PIDs of all processes in the group: [1415]
[2024-12-14T11:12:46.141+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1415
[2024-12-14T11:12:46.144+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-14T11:12:46.148+0000] {kafka_stream_data.py:129} ERROR - Error in main loop: Task received SIGTERM signal
[2024-12-14T11:12:46.374+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=kafka:9092 <connected> [IPv4 ('172.18.0.3', 9092)]>: Closing connection. KafkaConnectionError: Socket EVENT_READ without in-flight-requests
[2024-12-14T11:12:46.376+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2024-12-14T11:12:46.434+0000] {conn.py:380} INFO - <BrokerConnection node_id=0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.3', 9092)]>: connecting to kafka:9092 [('172.18.0.3', 9092) IPv4]
[2024-12-14T11:12:46.439+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.3', 9092)]> returned error 111. Disconnecting.
[2024-12-14T11:12:46.443+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.3', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-12-14T11:12:46.450+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2024-12-14T11:12:46.614+0000] {conn.py:380} INFO - <BrokerConnection node_id=0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.3', 9092)]>: connecting to kafka:9092 [('172.18.0.3', 9092) IPv4]
[2024-12-14T11:12:46.617+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.3', 9092)]> returned error 111. Disconnecting.
[2024-12-14T11:12:46.620+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.3', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-12-14T11:12:46.621+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2024-12-14T11:12:46.882+0000] {conn.py:380} INFO - <BrokerConnection node_id=0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.3', 9092)]>: connecting to kafka:9092 [('172.18.0.3', 9092) IPv4]
[2024-12-14T11:12:46.886+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.3', 9092)]> returned error 111. Disconnecting.
[2024-12-14T11:12:46.887+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.3', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-12-14T11:12:46.889+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2024-12-14T11:12:47.305+0000] {conn.py:380} INFO - <BrokerConnection node_id=0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.3', 9092)]>: connecting to kafka:9092 [('172.18.0.3', 9092) IPv4]
[2024-12-14T11:12:47.308+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.3', 9092)]> returned error 111. Disconnecting.
[2024-12-14T11:12:47.311+0000] {conn.py:919} INFO - <BrokerConnection node_id=0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.3', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-12-14T11:12:47.314+0000] {client_async.py:331} WARNING - Node 0 connection failed -- refreshing metadata
[2024-12-14T11:12:48.120+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-12-14T11:12:48.125+0000] {conn.py:315} ERROR - DNS lookup failed for kafka:9092 (0)
[2024-12-14T11:12:48.895+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-12-14T11:12:48.898+0000] {conn.py:315} ERROR - DNS lookup failed for kafka:9092 (0)
